### ISSUE TITLE
question about MEAN_COLOR

### ISSUE THREAD

**Issue by goodtogood** [wkcn/CSRNet-mx#1]
Hi,there
I noticed that model was converted from caffe model,
in your code mean color is
`MEAN_COLOR = mx.nd.array([92.8207477031, 95.2757037428, 104.877445883]).reshape((1, 3, 1, 1)) # BGR`
official repo mean color is set as bellow  [link](https://github.com/leeyeehoo/CSRNet-pytorch/blob/master/train.py#L118)

```
train_loader = torch.utils.data.DataLoader(
        dataset.listDataset(train_list,
                       shuffle=True,
                       transform=transforms.Compose([
                       transforms.ToTensor(),transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                     std=[0.229, 0.224, 0.225]),
                   ]), 
                       train=True, 
                       seen=model.seen,
                       batch_size=args.batch_size,
                       num_workers=args.workers),
        batch_size=args.batch_size)

```
[0.485, 0.456, 0.406]*255 =>123.675 , 116.28, 103.53
it's different, how come?
thanks!

**Comment by wkcn** [comment]
Hello!
The MXNet implementation in this repo uses the Caffe model.
The author trained the Caffe model using the mean value [92.8207477031, 95.2757037428, 104.877445883] by BGR order, refering to https://github.com/leeyeehoo/CSRNet/issues/1. And using this mean value could reach the result as the paper reported.
The PyTorch implementation uses different mean value to train CSRNet model.
